# Generated by Django 4.0.6 on 2022-07-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('link_1', models.CharField(blank=True, max_length=200, verbose_name='Ссылка 1')),
                ('link_2', models.CharField(blank=True, max_length=200, verbose_name='Ссылка 2')),
                ('link_3', models.CharField(blank=True, max_length=200, verbose_name='Ссылка 3')),
            ],
            options={
                'verbose_name': 'Книжная полка',
                'verbose_name_plural': 'Книжная полка',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('link_1', models.TextField(blank=True, max_length=200, verbose_name='Ссылка 1')),
                ('link_2', models.TextField(blank=True, max_length=200, verbose_name='Ссылка 2')),
                ('link_3', models.TextField(blank=True, max_length=200, verbose_name='Ссылка 3')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('name', models.TextField(max_length=200, verbose_name='Название')),
                ('gender', models.CharField(choices=[('Man', 'Мужской'), ('Woman', 'Женский'), ('Unisex', 'Unisex')], default=('Unisex', 'Unisex'), max_length=20, verbose_name='Гендорный признак')),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Мерч',
                'verbose_name_plural': 'Мерч',
                'ordering': ['-created_at', 'name'],
            },
        ),
    ]
