# Generated by Django 4.0.6 on 2022-09-12 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(max_length=11, verbose_name='Phone')),
                ('mail', models.CharField(max_length=100, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Заявка на покупку',
                'verbose_name_plural': 'Заявки на покупку',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='static/imgnews', verbose_name='Изображение')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('text', models.CharField(max_length=2000, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='static/imgstores', verbose_name='Изображение')),
                ('name', models.TextField(max_length=200, verbose_name='Название')),
                ('gender', models.CharField(choices=[('Man', 'Мужской'), ('Woman', 'Женский'), ('Unisex', 'Unisex')], default=('Unisex', 'Unisex'), max_length=20, verbose_name='Гендорный признак')),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Мерч',
                'verbose_name_plural': 'Мерч',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BookShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(default='default.jpg', upload_to='static/imgbooks', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('count', models.IntegerField(default=0, verbose_name='Количество книг у автора')),
                ('name_1', models.CharField(blank=True, max_length=20, verbose_name='Имя ссылки 1')),
                ('link_1', models.CharField(blank=True, max_length=200, verbose_name='Ссылка 1')),
                ('name_2', models.CharField(blank=True, max_length=20, verbose_name='Имя ссылки 2')),
                ('link_2', models.CharField(blank=True, max_length=200, verbose_name='Ссылка 2')),
                ('name_3', models.CharField(blank=True, max_length=20, verbose_name='Имя ссылки 3')),
                ('link_3', models.CharField(blank=True, max_length=200, verbose_name='Ссылка 3')),
                ('buyquery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudrin.buyquery', verbose_name='Заявка на покупку')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kudrin.review', verbose_name='Отзывы')),
            ],
            options={
                'verbose_name': 'Книжная полка',
                'verbose_name_plural': 'Книжная полка',
                'ordering': ['-created_at', 'name'],
            },
        ),
    ]
