# Generated by Django 4.0.6 on 2022-08-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudrin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/imgbooks', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/imgnews', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/imgstores', verbose_name='Изображение'),
        ),
    ]
