# Generated by Django 4.0.6 on 2022-08-16 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kudrin', '0002_bookshelf_image_alter_news_image_alter_store_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='link_1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='link_2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='link_3',
        ),
    ]
