# Generated by Django 4.0.6 on 2022-08-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudrin', '0003_remove_news_link_1_remove_news_link_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='name_1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Имя ссылки 1'),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='name_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Имя ссылки 2'),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='name_3',
            field=models.CharField(blank=True, max_length=20, verbose_name='Имя ссылки 3'),
        ),
    ]
