# Generated by Django 4.0.6 on 2022-08-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudrin', '0004_bookshelf_name_1_bookshelf_name_2_bookshelf_name_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество книг у автора'),
        ),
    ]
