# Generated by Django 4.0.6 on 2022-09-12 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kudrin', '0005_alter_review_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshelf',
            name='buyquery',
        ),
        migrations.RemoveField(
            model_name='bookshelf',
            name='review',
        ),
        migrations.AddField(
            model_name='buyquery',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kudrin.bookshelf', verbose_name='Книга'),
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kudrin.bookshelf', verbose_name='Книга'),
        ),
    ]
