# Generated by Django 4.0.6 on 2022-09-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudrin', '0006_remove_bookshelf_buyquery_remove_bookshelf_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
