# Generated by Django 4.0.6 on 2022-09-17 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kudrin', '0007_alter_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyquery',
            name='shirt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kudrin.store', verbose_name='Мерч'),
        ),
    ]
