# Generated by Django 4.1.10 on 2023-12-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudrin', '0010_alter_author_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ССылка'),
        ),
    ]
